---

repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.0a0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.15.0
    hooks:
      - id: yamllint

  - repo: https://github.com/willthames/ansible-review
    sha: v0.13.9
    hooks:
      - id: ansible-review
