---

repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.0a0
    hooks:
      - id: ansible-lint
        name: ansible-lint
        files: \.(yaml|yml)$
        args: [-c .ansible-lint]
        verbose: true

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.15.0
    hooks:
      - id: yamllint
        verbose: true

  - repo: https://github.com/willthames/ansible-review
    rev: v0.13.9
    hooks:
      - id: ansible-review
        name: ansible-review
        args: [-r ansible_lint/rules/]
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        verbose: true
