---
# For more information on Kerberos Authentication
# https://docs.ansible.com/ansible-tower/latest/html/administration/kerberos_auth.html
# Typically the domain is always upper case in the username

ansible_user: testuser@PRD.EXAMPLE.COM
ansible_password: "{{ vaulted_winrm_password }}"
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: kerberos
ansible_port: 5985 # HTTP (5985) or HTTPS (5986)
ansible_winrm_operation_timeout_sec: 480
ansible_winrm_read_timeout_sec: 600
